### ISSUE TITLE
aware/oblivious

### ISSUE THREAD

**Issue by annevk** [WICG/feature-policy#114]
Why does this need to be exposed? It'd help to have a note as on the face of it I'd say that this is not a thing we should have to care about.

**Comment by clelland** [comment]
This was exposed so that we could possibly define some features as having different behavior in a document which was written with the understanding that feature policy is a thing, vs a document which was written without that knowledge.

The example I've used is `document.write()` -- it currently has no failure modes, and there's no code in existence that expects it to not be defined, or to throw an exception, or even to just silently fail. So maybe we can't ever make it fail in documents that are on the web today. But if a document is served with a Feature-Policy header that explicitly mentions "docwrite", then its much more safe to assume that the developer was aware that `write()` has a way to fail, and would have coded the page with that in mind.

**Comment by annevk** [comment]
In that case you'd check for the "docwrite" feature? I think I sorta get what you mean, but it seems we'd have to block things from day 1 to make this stick.

**Comment by clelland** [comment]
Right -- new content could check for it,certainly, or catch an exception, or whatever was appropriate. I just don't know if you could ever safely take the feature away from old content.

**Comment by annevk** [comment]
We tried this before, e.g., with document.domain, and nobody was willing to couple their new feature to the removal of that, so in the end it didn't work. (That's also largely why we have Feature Policy to begin with I suppose, because we can't really figure out a "correct mode" that works for everyone.)

**Comment by clelland** [comment]
Removed from spec in 626ff9591aed540ce81e01b9d90e9b5680795bea as there are no current or proposed uses of the definitions.
