### ISSUE TITLE
Define disable policy for Permissions API?

### ISSUE THREAD

**Issue by igrigorik** [WICG/feature-policy#14]
An idea/request from @jyasskin:
- Provide a mechanism to disable Permissions API - i.e. no prompts on this origin!
- Enforcement: don't hide the interface but return all requests as "denied".
  - ... is it possible to extend this to whitelist what prompts are allowed? E.g. disable all prompts except Geolocation?

**Comment by jyasskin** [comment]
This is broader than the Permissions API, whose [`request()`](https://w3c.github.io/permissions/#permissions-interface) method is just a uniform interface to functions that exist elsewhere.
```
Feature-Policy: {"disable":["permissions"]}
```
should be equivalent to
```
Feature-Policy: {"disable":["geolocation", "midi", "notifications", "push", "webrtc"]}
```
except that if a future permission is added to the spec, it would be included in the disable list rather than omitted.

Both `Feature-Policy: {"disable":["permissions"]}` and `Feature-Policy: {"disable":["geolocation"]}` should leave `navigator.permissions.query({name: 'geolocation'})` and `navigator.permissions.request({name: 'geolocation'})` accessible and cause them to return `{state: 'denied'}`.  On the other hand, `navigator.geolocation.getCurrentLocation()` shouldn't be accessible with either.

----

A possible syntax for re-enabling selected permissions is:
```
Feature-Policy: {"disable":["permissions"]}, {"enable":["geolocation"]}
```
which would be equivalent to
```
Feature-Policy: {"disable":["midi", "notifications", "push", "webrtc"]}
```

**Comment by igrigorik** [comment]
Yay, moar features to spec! Seriously though.. sounds reasonable. I like it.

@mikewest @raymeskhoury @noncombatant wdyt?

**Comment by raymeskhoury** [comment]
Overall sgtm :)

**Comment by igrigorik** [comment]
We're solving this case via "empty whitelist" approach -- see https://github.com/WICG/feature-policy/issues/43. Closing.
