### ISSUE TITLE
Rename document.policy to document.featurePolicy

### ISSUE THREAD

**Issue by johannhof** [WICG/feature-policy#216]
On Firefox side we would greatly prefer document.policy to be called something else, maybe document.featurePolicy. This avoids the ambiguity with CSP and friends.

(https://wicg.github.io/feature-policy/#document-policies)

cc @ckerschb @bakulf

**Comment by johannhof** [comment]
This concern mostly came from @ckerschb, so I'll ask him to chime in on the idea.

If this is the desired end state of the API, isn't it incompatible with the `policy.allowsFeature()` approach that's currently in the spec?

**Comment by ckerschb** [comment]
> So in the future we might have something like
> 
> ```
> document.policy.csp["script-src"] => ["self", "https://*.example.com/*"]
> document.policy.sandbox => ["forms", "presentation-lock", ... ]
> ```

I like that idea! Though, for feature policy we would end up with something like the following:
> document.policy.featurepolicy.allowsFeature()
right?

If we go down that route I am fine with it and we have to update the spec to reflect that change. If we only end up having document.policy being used for feature policy then I guess we should rename it to document.featurepolicy, otherwise it's ambiguous and might cause confusion and problems.

**Comment by clelland** [comment]
I've made an update to the spec to change that to `document.featurePolicy` -- we don't have any concrete plans to extend it past that right now. WDYT, @johannhof, @ckerschb?

(I've also added a `.features()` method to get *all* supported features, as we've had people asking for that, and removed the `.unstable` class from the spec sections)

**Comment by ckerschb** [comment]
Yeah, that looks good, thanks - FWIW, I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1514296 to get that updated in Firefox.

**Comment by clelland** [comment]
Thanks! I'll make the merge.
