### ISSUE TITLE
(Probably?) insecure featurePolicy inherit algorithm

### ISSUE THREAD

**Issue by bakulf** [WICG/feature-policy#233]
While debugging my Firefox implementation of FeaturePolicy, I realized that FeaturePolicy inherit algorithm seems to be insecure. Here an example:

a. top-level document https://site.com receives a HTTP header: Feature-Policy: fullscreen 'self'
b. the document loads a 3rd party script: https://example.com/a.js
c. that script creates this iframe: <iframe src="https://example.com/foobar" allow="fullscreen '*'">

following the spec, example.com/foobar is allowed to use fullscreen feature, which is what the top-level document doesn't want. It seems that, there is no way, for the document, to enforce fullscreen to be used just by it-'self'.

10.9.3.1 should change to:

If the allowlist for feature in container policy matches origin, and the allowlist for feature in the parent policy matches origin, return "Enabled".

**Comment by bzbarsky** [comment]
The same thing happens if the toplevel thing sends `Feature-Policy: fullscreen 'none'` as well, right?

@clelland Is that expected behavior?

**Comment by clelland** [comment]
The expected behaviour is that any time the feature is enabled in the document, the document can delegate that feature to the frames that it chooses. (This fits with the idea that the default allowlist is `'self'`, for many features, but the document can use the allow attribute to delegate to specific frames without *also* having to set a header allowing those origins.)

For most features, an untrusted script could also just add a channel to communicate with the child frame, to effectively grant it access to the feature. The only way to really stop that is to not have the feature available in the parent page at all. (The principle that we ended up with here is that if you grant a frame access to a feature, you have to trust it with the power to delegate that feature to its children -- and this principle applies to the top-level document as well)

@bzbarsky, I think that behaviour should be changed for the `'none'` case -- if it is disabled in the parent document, then the parent shouldn't be able to delegate. I used to think differently: that a page should be able to decline the use of a feature but retain the ability to delegate it on a frame-by-frame basis, but that does open up the possibility of an XSS bug rendering the protection offered by FP useless.

This would mean that the allow attribute can be used to grant a feature to a frame, as long as either the parent has access to the feature, or the feature was granted to the child frame's origin with the `Feature-Policy` header.

In that case, 10.9.3.1 should say something like
> If the allowlist for *feature* in *container policy* matches *origin*, then:
> 1. If *feature* is enabled in *parent* for *origin*, then return `"enabled"`
> 2. If *feature* is enabled in *parent* for *parent*'s *origin*, then return `"enabled"`

We could probably refactor that algorithm to make that a little more straightforward.

**Comment by clelland** [comment]
There is also another issue with the algorithm as written:

If a page at https://example.com is delivered with a feature policy header like this:

    Feature-Policy: fullscreen https://example.net

Then this iframe will be allowed access to fullscreen:

    <iframe src="https://example.net/"></iframe>

While this one will have it *disabled*:

    <iframe src="https://example.net/" allow="fullscreen"></iframe>

(10.9.4 correctly enables the feature in the first case, while 10.9.3.2 incorrectly disables the feature in the second case)

**Comment by bzbarsky** [comment]
> while 10.9.3.2 incorrectly disables the feature in the second case

Why, exactly?  I'm not quite quite following.  In 10.9.3.1 parent's inherited policy will be "Enabled", no?  It's not affected by the HTTP header...

**Comment by clelland** [comment]
Sorry, @bzbarsky -- I actually noticed the behaviour after I switched it from using the parent's inherited policy (which, as you pointed out in https://github.com/WICG/feature-policy/issues/233#issuecomment-431388954, fails to block the child with a header value of 'none') to testing whether the feature was enabled in the parent.

**Comment by bzbarsky** [comment]
Ah, ok.

I have to admit to getting a little lost in terms of the overall "what behavior do we want?" goal at this point...
