### ISSUE TITLE
Clearly define how the policies of embedded documents combine/interact

### ISSUE THREAD

**Issue by raymeskhoury** [WICG/feature-policy#28]
A top level document can have a policy that it sets which apply to itself and its children. It may have embedded documents (in iframes) that also have policies which they sets. These iframes may themselves embed documents which also have policies. We need to define how these things get composed/cascade down the frame tree.

**Comment by igrigorik** [comment]
@raymeskhoury I believe this is already covered by: http://wicg.github.io/feature-policy/#initialize-for-global. In particular, see "If global is a Window and its Document has a parent browsing context or opener browsing context".. 

Does that address your question?

**Comment by igrigorik** [comment]
Spent the morning staring at this bug + https://github.com/WICG/feature-policy/issues/26 and https://github.com/WICG/feature-policy/issues/12. Here's what I've come up with so far...

----

(1) For each feature, define default enable {top level, nested} policy, and disable policy. E.g..

```
Feature     |     Enable      | Disable
            | top    | nested |
------------------------------|----------
docwrite    |  *     | *      |
sync-xhr    |  *     | *      |
webrtc      |  *     | *      |
geolocation |  self  |        |
```

Above defaults say that docwrite has default "enable" policy of "*" (i.e. all origins) in both the top level and nested context; default disable policy is null. Geolocation, on the other hand, has a default enable policy of "self" for top-level context (i.e. enabled) and null otherwise (disabled).

(2) We define algorithms to query if feature is enabled, update rules...

**Is feature X enabled for context?**
  - Let origin be the origin of context
  - Does disable origin-list for X contain origin?
    - If `true`, return `disabled`
  - Does enable origin-list for X contain origin?
    - If `false`, return `disabled`
  - Return `enabled`

**Update context's policy with rule Y**
- For each `{feature, mode, new-origin-list`} tuple in rule Y:
  - _Is feature enabled for context?_
    - If `disabled`, abort these steps.
  - Set feature mode's origin list to `new-origin-list`.

We also need an algorithm to initialize the rules for nested contexts.. 

```
example.com sets...
  {disable: [docwrite, sync-xhr], target: [*]}
  {enable: [geolocation], target: [A]}
  {enable: [webrtc], target: [self, B]}

  Resulting feature policy table:

  feature     |  Enable       | Disable
  ----------------------------|------------------
  docwrite    |  *            | *
  sync-xhr    |  *            | *
  webrtc      |  self, B      |
  geolocation |  A            |

  <iframe src=A>
    1) Initialize default table (using nested defaults column)

      feature     |  Enable       | Disable
      ----------------------------|------------------
      docwrite    |  *            |
      sync-xhr    |  *            |
      webrtc      |  *            |
      geolocation |               |

    2) Copy disable rules from parent
    3) For each parent's enable {feature, origin-list} tuple:
      - Let origin be the origin of nested context
      - If parent's tuple matches context's tuple, go to next rule
      - Else, set enable origin-list for feature to:
        - If parent's enable origin-list for feature contains origin
          - [origin] if default origin-list is empty   // default off features
          - ["*"] if default origin-list is "*"        // default on features
        - empty list otherwise

      feature     |  Enable       | Disable
      ----------------------------|------------------
      docwrite    |  *            | *
      sync-xhr    |  *            | *
      webrtc      |               |
      geolocation |  A            |

 <iframe src=B> 
      feature     |  Enable       | Disable
      ----------------------------|------------------
      docwrite    |  *            | *
      sync-xhr    |  *            | *
      webrtc      |  *            |
      geolocation |               |
```

Phew.. I think the above satisfies all the requirements:
- Developers can blacklist features on per-origin basis.
  - Blacklist automatically cascades to all nested contexts.
- Developers can whitelist features on per-origin basis.
  - Some enabled features automatically cascade down (if they're default on in nested context)
  - Some enabled features need to be explicitly delegated for each sub-context

Also, I believe above also handles policy precedence: parent > header > meta > attribute.
 - Parent's policy is applied when nested context is initialized
 - Header policy is applied next and can further constrain the policy
 - Meta policy runs next and can futher...
 - Attribute policy gets last chance

Because the above are run in specific order (headers processed first, head section next, attributes last), earlier updates to the policy constrain later updates.. e.g. if parent allows feature and headers disable a feature, then meta/attribute policies for that feature are ignored.

---

@raymeskhoury @clelland First, sorry about the length! Second.. does this make sense to you? We can VC if its easier to hash through this..

**Comment by clelland** [comment]
A few things here aren't clear to me --

(1) Defaults:

What is the difference between `*` and `self` in the top-level enable policy? How would a line like

    Feature     |     Enable      | Disable
                | top    | nested |
    ------------------------------|----------
    geolocation |  self  |        |

be different from 

    Feature     |     Enable      | Disable
                | top    | nested |
    ------------------------------|----------
    geolocation |  *     |        |

I'm not sure how the top-level origin can match anything other than '`self`', I guess.

Also, how and when would the default disable policy be used? It's blank in all of the examples; do we need to define a default disable policy for features, or is null always going to be correct?

(2) Algorithms

The **Is feature X enabled for context?** algorithm appears to default to `enabled`, but I don't see how this explains the default behaviour for Geolocation ("...a default enable policy of "self" for top-level context (i.e. enabled) *and null otherwise (disabled).*") -- it seems to me that a null disable policy would cause this algorithm to return `enabled` instead.

The **Update context's policy with rule Y** algorithm seems to allow origins to override their parent's disable lists. I may be reading it wrong, or misunderstanding when it is supposed to be applied, but it looks to me like this situation is possible:

1. Top-level document A (a.com) includes a feature policy that enables a feature for b.com, and disables it for z.com.
2. Document A embeds document B in a frame (from b.com)
3. Document B includes a feature policy that enables the feature for itself, and for z.com.

Now, when we update the B frame's context's policy with B's rules, the feature is *not* disabled, so we follow the step that says "Set feature mode's origin list to `new-origin-list`." -- does this mean that the feature is now enabled for z.com, despite the wishes of document A? (Or is this situation actually supposed to be handled by a different algorithm?)

(3) Nested contexts

* "For each parent's enable {feature, origin-list} tuple:" Does "each parent's" mean that we look at multiple parents? i.e. traverse the frame tree to the root? Or does it mean "for each enable tuple of this frame's parent context"?

I think I have more questions about step 3, but they'll probably depend on the answer to that one.

**Comment by igrigorik** [comment]
> What is the difference between * and self in the top-level enable policy?

The difference is how the policy cascades down: if the default is "*" then it's automatically propagated down to nested contexts; if the default is enabled for top-level only, then we start with `self` and only propagate the permission if nested context is same-origin, or if the top-level context explicitly delegated permission to the child's origin.

Also, apologies, I introduced a bit of confusion here... Note that in the processing model we substitute "self" with the global's origin [step 3.2.1](http://wicg.github.io/feature-policy/#parse-policy-from-value-and-global), so when you read the table, you should just substitute 'self' with resolved value of the origin.

> Also, how and when would the default disable policy be used? It's blank in all of the examples; do we need to define a default disable policy for features, or is null always going to be correct?

Yeah, it's blank by default for all the features.. and in theory we could omit it, but I thought it might be helpful to be explicit about it. The other argument is that origin-policy describes features that fall into this bucket, so it helps to be explicit, since we plan to integrate the two.

> The Is feature X enabled for context? algorithm appears to default to enabled, but I don't see how this explains the default behaviour for Geolocation ("...a default enable policy of "self" for top-level context (i.e. enabled) and null otherwise (disabled).") -- it seems to me that a null disable policy would cause this algorithm to return enabled instead.

Does my earlier comment of resolving `self` to global's origin clear this up? 
- We resolve default policy of `self` to origin (e.g. "A")
- If page set an explicit disable policy for A then "disabled".
- Enable origin-list contains "A", hence "enabled".

> Now, when we update the B frame's context's policy with B's rules, the feature is not disabled, so we follow the step that says "Set feature mode's origin list to new-origin-list."

1. We propagate parents's policy into child context before anything else is initialized: [step 5.1.1](http://wicg.github.io/feature-policy/#initialize-for-global) -- note, requires updates.
1. Then we process the (child) response policies (header, meta, attributes). 
 - If parent's policy disabled the feature we bail on update.
   - If feature is default enabled for top-level only and parent didn't delegate permission, then child's  enable policy won't contain it's origin, hence feature is disabled.
 - Otherwise, feature is enabled and child can delegate and/or restrict it further.

**Comment by raymeskhoury** [comment]
Thanks for posting this @igrigorik  :) I just started taking a look. I too am confused about the difference between self and * for the default policy. It feels like we just need to say whether something is enabled or not in a top level context and whether it is enabled or disabled by default in a nested context. To go back to Ian's example, what would be practically different between geolocation having self or * for the top level default policy? 

Also I'm unclear about the default disable policy. Wouldn't a null enable policy be equivalent to having a disable policy?

**Comment by igrigorik** [comment]
> To go back to Ian's example, what would be practically different between geolocation having self or * for the top level default policy?

- `self` means geolocation is enabled for top-level context and none of the nested contexts
- `*` means geolocation is enabled for top-level context and all of the nested contexts 

These are very different. Or, am I missing your question? We can chat on VC later today..

> Also I'm unclear about the default disable policy. Wouldn't a null enable policy be equivalent to having a disable policy?

Why is that a concern?

**Comment by clelland** [comment]
> > To go back to Ian's example, what would be practically different between geolocation having self or * for the top level default policy?

> * self means geolocation is enabled for top-level context and none of the nested contexts
> * means geolocation is enabled for top-level context and all of the nested contexts

So, are these two equivalent?

    Feature     |     Enable      | Disable
                | top    | nested |
    ------------------------------|----------
    geolocation |  self  |  *     |



    Feature     |     Enable      | Disable
                | top    | nested |
    ------------------------------|----------
    geolocation |  *     |        |

> We can chat on VC later today..

Sounds like a good idea.

**Comment by igrigorik** [comment]
@clelland oh, I think I see the confusion. The table you're using is the initialization table, you'd only use a single (enable) defaults column depending on whether we're initializing a top-level or nested context... Hence the single enable | disable columns in my later example. 

There is probably a cleaner way to explain all this.. open to suggestions!

**Comment by igrigorik** [comment]
We're converging on simplifying the whole thing and using a "whitelist model". Details in the explainer: https://docs.google.com/document/d/1k0Ua-ZWlM_PsFCFdLMa8kaVTo32PeNZ4G7FFHqpFx4E/edit - let's continue the discussion there.
