### ISSUE TITLE
[TAG] Inheritance may be unnecessarily confusing

### ISSUE THREAD

**Issue by triblondon** [WICG/feature-policy#67]
[From TAG review](https://github.com/w3ctag/design-reviews/issues/159)

The cascade effect of parent header > allow attribute > iframe header is confusing. For example, if a parent document defines vibrate: ["self"], the iframe has allow="vibrate", and the iframe policy header has vibrate:[], then we believe this will prohibit vibrate in the iframe, but since the allow attribute is more visible to the developer this may cause significant head scratching. We wonder how compelling are the use cases for the attribute, given the expressiveness of the header?

**Comment by clelland** [comment]
> if a parent document defines vibrate: ["self"], the iframe has allow="vibrate", and the iframe policy header has vibrate:[], then we believe this will prohibit vibrate in the iframe

Yes, that's correct. Any frame is free to disable a feature for itself. The parent frame doesn't force the feature on in the child, instead it grants the ability to use the feature to the child.

> but since the allow attribute is more visible to the developer this may cause significant head scratching

Is that any different than the scenario where the parent at **a.com** includes the header `{"vibrate": ["self", "b.com"]}`, and then the iframe at **b.com** includes the header `{"vibrate": []}` ?

In both cases, the parent grants access to vibrate to the child, and then child, unknown to the parent, declines that access. I don't think the way that the parent grants access (header vs iframe attribute) makes it any different.

> We wonder how compelling are the use cases for the attribute, given the expressiveness of the header?

This is probably best answered by seeing whether developers choose to use the attributes vs headers. My thoughts are:

* The header is certainly more expressive, but not all developers have access to it. 
* Iframe attributes are already used on the web plaform, for controlling fullscreen and paymentrequest features, and I'd like to be able to express those (and others) with FP
* Iframe attributes are more expressive in one way -- they can target specific frames, and make exceptions to the header policy on a frame-by-frame basis. (Only to change deny->allow right now, but we're working on a more general syntax to enable the reverse as well)

**Comment by raymeskhoury** [comment]
I strongly believe the attributes are necessary in order to make the feature successful. 2 reasons:
-Not all developers have the ability to modify headers. Think of hosting services where you only control the content of the page and not the headers. It could be a very big headache to some developers if they need to modify headers which they have no control over.
-Websites that provide widgets for other websites to use very often provide code snippets which developers can copy and paste into their page. Think of Google maps or Youtube embeds. Developers providing these code snippets may need to re-enable features in the iframes they are embedding in order for their content to work properly (take location as an example). These use cases will break if we do not provide a way to re-enable features in the iframe attribute (or some similar mechanism).
