### ISSUE TITLE
[TAG] Interaction with New Features

### ISSUE THREAD

**Issue by slightlyoff** [WICG/feature-policy#69]
[From TAG review](https://github.com/w3ctag/design-reviews/issues/159)

The default behaviour of new features added in the future must depend on the shipping status of the feature in the platform. For example, if a document.write policy is added it must "fail open" in order to avoid breaking existing websites, and therefore the only safe scenario in which a feature could be introduced with a closed default status if is if support for the feature in feature policy is a required part of shipping the feature itself. Is there a mechanism for tying together the introduction of a feature in the platform and the addition of a new token to this specification? (see also registry point)

**Comment by clelland** [comment]
> if a document.write policy is added it must "fail open" in order to avoid breaking existing websites

That's correct -- if we take an existing, ubiquitous web feature, such as document.write, and put it under policy control, we need to make its default allowlist `["*"]`, or else much existing content will be broken.

> therefore the only safe scenario in which a feature could be introduced with a closed default status if is if support for the feature in feature policy is a required part of shipping the feature itself

Also true -- a default allowlist of `[]` would mean that you *have* to use feature policy in order to enable the feature in *any* context.

The middle-ground of `["self"]` can be used for new features in a couple of ways -- you can fully integrate with feature policy, or you can accept that it is available at the top-level and not in cross-origin frames (any browser implementer could do that even without implementing any support for FP), or you could fake it without supporting FP by recognizing `<iframe allow="newfeature">` to enable the feature in cross-origin frames, much like `allowfullscreen` is handled today.

> Is there a mechanism for tying together the introduction of a feature in the platform and the addition of a new token to this specification?

No, there's currently no such mechanism. We could provide guidance on this, if that is appropriate.

Adding a token to this spec should be done by reference, I think -- I'd like the feature list appendix here to be non-normative, and simply a guide to features which are defined in other specs, which any browser may or may not support. Ideally, other specs can simply say something like

    The *foo* API is a policy-controlled-feature [See FEATURE-POLICY],
    with a feature name keyword of "foo". The default allowlist is ["self"].

and then go on to define the behaviour when enabled / disabled by policy. (Exact wording TBD)

**Comment by raymeskhoury** [comment]
We chatted about this in the last meeting we add. We're not quite sure the exact concern being raised. Maybe you could clarify?

Is the problem that we want to encourage people adding new features to be aware of Feature Policy - specifically:
a) To be able to add their feature to feature policy if it makes sense
b) To be considering how the feature should fail safely and appropriately if it is disabled by policy

If that is the concern, then I agree that it would be good for people to be aware of this. Off the top of my head I can't think of a simple criteria to guide people here about when it's right to add their feature to feature policy. I think most of the features we've had in mind tend to fall into 1 of 4 categories:
1) They have security/privacy implications (e.g. geolocation)
2) They have performance implications (e.g. sync xhr)
3) They have potential for user annoyance (e.g. vibrate)
4) They are legacy features we would like to deprecate on the platform

**Comment by clelland** [comment]
Closing this, I think the relevant points are addressed in the integration.md document -- please feel free to open new issues for anything that still isn't covered
