### ISSUE TITLE
Extend "allow" attribute on iframes to support complete syntax 

### ISSUE THREAD

**Issue by LoonyBean** [WICG/feature-policy#78]
See previous discussion for "allow" attribute here https://github.com/WICG/feature-policy/issues/11

I scratched a design doc here: https://docs.google.com/a/chromium.org/document/d/1903nztB5tHN_8g_GDtNT9KkkjRAuid1eaS8kT99mlDs/edit?usp=sharing
Please take a look and all insights are appreciated!

**Comment by LoonyBean** [comment]
@loonybear

**Comment by loonybear** [comment]
After some discussion (please refer to the [design doc](https://docs.google.com/document/d/1903nztB5tHN_8g_GDtNT9KkkjRAuid1eaS8kT99mlDs/edit?usp=sharing) for more details), we decided to adopt the syntax below:
```html
<iframe src="https://example.com" allow="vibrate https://a.com https://b.com; fullscreen 'none'; payment 'src'; payment; usb '*'">
```
- Adapting [CSP syntax](https://content-security-policy.com/), with an additional wildcard ```'src' ```. See below for the interpretation of each wildcard:
    + ```"*"```: Feature is enabled on all origins
    + ```"none"```: Feature is disabled
    + ```"self"```: Feature is enabled on the origin of the containing document
    + ```"src"```: Feature is enabled on the origin of the URL in the iframe’s src attribute
- Each token is separated by a semicolon, and each token is in the format of ```key value1 value2 value3```, where values are optional and space-separated, wildcards (e.g., ```‘*’, ‘none’, etc```) are wrapped by single-quotes.
- Only fully-specified origins, like "https://cdn.com", or with a port like "http://example.com:8000", are supported.
- ```payment;``` and ```payment 'src';``` are equivalent.
- Customized CSP parser applying [policy parsing algorithm](https://wicg.github.io/feature-policy/#parse-policy-directive) would be required.

#### Pros
- minimizing additional custom parser (as the CSP parser will be used)
- good practice from a security perspective
- sharing same syntax with a known web feature (CSP) will make it easier for web developers to adapt

#### Cons
- no longer supporting current syntax:
```html
<iframe src="https://example.com" allow='vibrate payment usb'>
```
the new equivalence would have to be semicolon-separated:
```html
<iframe src="https://example.com" allow='vibrate; payment; usb'>
```

#### Note
This also means that the syntax for [feature policy HTTP header policy](https://wicg.github.io/feature-policy/#feature-policy-http-header-field) will also be updated for consistency purposes. 



This is the [link to the original design doc](https://docs.google.com/document/d/1903nztB5tHN_8g_GDtNT9KkkjRAuid1eaS8kT99mlDs/edit?usp=sharing)

**Comment by clelland** [comment]
@mikewest @domenic -- Does this match roughly what you were expecting to see from an adaptation of the CSP syntax?

**Comment by domenic** [comment]
LGTM, although I wonder what the `payment 'src'; payment;` in the example is supposed to do. I guess the latter payment overrides the former, causing it to be supported nowhere?

**Comment by igrigorik** [comment]
So this removes the JSON bits entirely? One of the original reasons for JSON syntax was to improve developer ergonomics: easier to understand, trivial to author, validate, and parse with existing tools, etc. Are we confident that CSP style syntax is the better outcome in that regard?

**Comment by clelland** [comment]
@igrigorik, essentially, yes. JSON is ergonomic right up until the point where we want to put it inside of an HTML attribute value. At that point, I think the calculus changes -- escaping issues start to overtake the familiarity of the format, especially for anyone writing tags without tooling. At the same time, you can't get anywhere near the ergonmics of

    <iframe allow="vibrate; payment; usb">

if you need to specify, in JSON,

    <iframe allow='{ "vibrate": ["src"], "payment": ["src"], "usb": ["src"] }'>

since quotes are required, and objects can't have default values for keys.

I don't think CSP is perfect; I'd prefer a syntax that allowed us to forego the semicolons as separators in  the simplest possible case, but it's a pretty good fit that doesn't require specifying a completely new grammar, and introducing another syntax into HTML.

**Comment by loonybear** [comment]
Re domenic@
The ```payment 'src'; payment;``` is just an example to show the 2 equivalent ways of allowing payment on ```'src'```.

**Comment by raymeskhoury** [comment]
Overall I think this is a good path forward if CSP folks are ok with it. If we decide to do this though, we might want to make a short-term fix that migrates the currently shipped allow attribute to parse semi-colon separated keywords instead of the current space-separated keywords (since other things are depending on this). @clelland would that be possible?

**Comment by clelland** [comment]
@raymeskhoury, we're actually planning on doing the reverse -- switching to the new syntax, and adding a temporary fallback for the original space-separated keywords. The current plan is to try to parse the string as a space-separated list of "alphanumeric-not-origins", essentially. If it matches that, and contains at least two items, then we'll presume that the author intended all of the items to be feature names, and will parse it as such. (And emit a standard deprecation warning)

Otherwise, we'll assume that the new syntax - that the space separates a feature name from its list of origins (CSP-style) and parse it that way.

**Comment by raymeskhoury** [comment]
SGTM thanks for the heads up :)

**Comment by reschke** [comment]
Well, I'm pretty sure the new syntax has several flaws; for instance, did you consider:

- quoted-string semantics,
- allowable characters in URIs (note tha tURIs can contain both "," and ";")

etc.

**Comment by clelland** [comment]
Thanks, @reschke -- Maybe this ABNF isn't as tight as it should be.

I had quickly scanned RFCs 3986 and 6454 for obvious issues -- ';' and ',' are both reserved chars, but on second look, definitely allowed either as 'IPvFuture' or 'reg-name', though they're certainly not allowed in DNS-resolvable hostnames.

I suppose that we need to escape such characters somehow -- I was going to add a note about PunyCode for IDN, but I don't think that covers characters < 7F at all. I'll have to look more closely at how CSP handles this situation.

**Comment by reschke** [comment]
FWIW,

  http://example.com/a,b;c

is a valid URI.

**Comment by clelland** [comment]
That's true, but we're trying to restrict the items in the allowlist to keywords and origins (specifically, their ASCII serializations, from [6454](https://tools.ietf.org/html/rfc6454#section-6.2))

So in a policy directive, you could include http://example.com or http://example.com:8000, but not http://example.com/index.html or http://example.com/a,b;c

(At least that's the intention, and how I've tried to write it in the PR)

**Comment by craigfrancis** [comment]
@LoonyBean @clelland - Would it be possible to get the spec updated with the new syntax?

All the examples are JSON based, and section 5.1 describes JSON serialization:

https://wicg.github.io/feature-policy/

Just for reference, this has been implemented in Chrome 62, and will be released 17th October 2017.

BTW, thanks for adding this feature.

**Comment by loonybear** [comment]
@craigfrancis Yes, we are working on it.

**Comment by clelland** [comment]
#83 is the pull request with the updated syntax and examples, I think I need to make a couple of tweaks to ensure that its clear that only origins are allowed in the allow lists.

**Comment by craigfrancis** [comment]
Thanks, and sorry I didn't check the pull requests.

**Comment by craigfrancis** [comment]
Minor tweaks...

["*"] x 4
["self"] x 2
[] x 1

Section 8.1, step 2 (separated by commas) and step 3 (leading "[" ... and a trailing "]").

And as already noted, sections 8.2 and 8.3 need updating :-)

**Comment by jdalton** [comment]
If `allow=""` is empty does that `none` all the features?

**Comment by craigfrancis** [comment]
@jdalton, you need to specify which features you want to limit, as you never know what might be added in the future.

For example, if/when [`sync-script`](https://github.com/w3c/webappsec-feature-policy/issues/135) is introduced, if `allow=""` did disable all features, this would suddenly break those websites that aren't using `defer` or `async` attributes on all of their script tags.
