### ISSUE TITLE
Clarify integration with HTML

### ISSUE THREAD

**Issue by clelland** [WICG/feature-policy#95]
From https://github.com/whatwg/fullscreen/issues/106#issuecomment-344915565:
> I don't understand how 4 in https://wicg.github.io/feature-policy/#integration-with-html works.

This text needs to be more clear, and needs to be suitable for actual integration into HTML. The existence of a policy attached to a document needs to be defined somewhere, as well as precisely what it means for a feature to be 'indicated by `allowattribute`'. 'Enables' should probably be linked explicitly to that algorithm as well.

**Comment by annevk** [comment]
I also ran into this together with @rebeccahughes in https://github.com/whatwg/html/pull/3253 as well. You need to define that documents and workers (what about worklets?) have an associated set of sorts. Then we can easily grab that and perform a [contains test](https://infra.spec.whatwg.org/#list-contain) on it of sorts.

**Comment by clelland** [comment]
Re: Worklets, I haven't come up with a use case for associating a feature policy with them yet.
None of them seem to share any browser APIs with documents, they can't spawn any new execution contexts of their own (which might necessitate at least passing a policy along), and they already have a very restricted set of features available.
It may be worth defining in the future, but I just can't see the use right now.

**Comment by annevk** [comment]
Well, I saw you wanted to explain `<iframe sandbox>`; perhaps you want to be able to explain CSP too, in which case you need to be able to disable `eval()` in worklets.

**Comment by rebeccahughes** [comment]
We discussed this in more detail here: https://groups.google.com/a/chromium.org/forum/?hl=en#!topic/blink-dev/sufZCxRTvXk

Summary of action points:

- [ ] Documents need to be defined to have an actual policy object, and there are two places where that needs to be initialized. (Current text incorrectly refers to 'global objects')
- [ ] The document's allow* flags are no longer relevant, and allowfullscreen, allowpaymentrequest and allowusermedia need to reference FP instead. (Allowusermedia needs to be handled as well)
- [ ] The 'allowed to use' algorithm needs to actually take a policy-controlled feature as an argument, and not just "feature indicated by *some attribute*", so that other specs can properly call into it.
- [ ] We should either formalize how FP operates on workers/worklets, or remove that from the spec for now.

**Comment by clelland** [comment]
Also:

- [ ] The `allow` attribute needs to be defined on the `iframe` element.
